title: Canasta Básica Total Estudiantil
logo: /assets/img/logo.jpg
description: Proyecto autogestivo estudiantil para estimar los costos reales de estudiar en la UNC
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
