title: Canasta Básica Total Estudiantil
logo: /assets/img/logo.jpg
description: Elaborado por y para estudiantes
show_downloads: true
is_project_page: true
google_analytics:
theme: jekyll-theme-minimal
